### ISSUE TITLE
Is the license GPL or MIT?

### ISSUE THREAD

**Issue by Ian-Foote** [mckinseyacademy/django-upload-validator#16]
The [`LICENSE` file is GPL](https://github.com/mckinseyacademy/django-upload-validator/blob/ebbbfac1f37d25ffba16c62265cd2d206c7a2762/LICENSE), but [`setup.py` specifies the license as MIT](https://github.com/mckinseyacademy/django-upload-validator/blob/ebbbfac1f37d25ffba16c62265cd2d206c7a2762/setup.py#L20). Can you clarify which license is actually correct?

**Comment by naeem91** [comment]
It is GPL. The one specified one setup.py is incorrect. Thanks for pointing out.
