### ISSUE TITLE
No PyPi version

### ISSUE THREAD

**Issue by e-kolpakov** [mckinseyacademy/django-upload-validator#7]
Packages not published on PyPi are harder to install as dependency properly (requires providing [dependency_links](https://github.com/open-craft/xblock-group-project-v2/blob/master/setup.py#L39) which considered somewhat harmful as it ties otherwise declarative `setup.py` to concrete repository implementation).

Also, by default `pip` does not automatically resolve dependencies given via `dependency_links`, so any packages (i.e. group-project-v2) that depend on `django-upload-validator` will likely fail to install without explicitly listing `django-upload-validator` as a dependency. In short - `pip` by default does not resolve transitive dependencies without PyPi version.

So, please release PyPi version. (Ideally from CI build, but manually should be fine as well).

**Comment by naeem91** [comment]
@e-kolpakov [PyPi version](https://pypi.python.org/pypi/django-upload-validator) has been released. Now it can be installed from `pip install django-upload-validator`
